$(document).ready(function() {

	$('.one').click(function(){
		$('.one').css('background-color','#f2d179');
		$('.two').css('background-color','#fdeab7');
		$('.three').css('background-color','#fdeab7');
		$('.four').css('background-color','#fdeab7');
		$('.five').css('background-color','#fdeab7');
		$('.six').css('background-color','#fdeab7');
		$('.sidebar').fadeIn(1000);
		$('.sidebar2').hide();
		$('.sidebar3').hide();
		$('.sidebar4').hide();
		$('.sidebar5').hide();
		$('.sidebar6').hide();
		$('.group').show();
		$('.group2').hide();
		$('.group3').hide();
		$('.group4').hide();
		$('.group5').hide();
		$('.group6').hide();
	});

	$('.two').click(function(){
		$('.one').css('background-color','#fdeab7');
		$('.two').css('background-color','#f2d179');
		$('.three').css('background-color','#fdeab7');
		$('.four').css('background-color','#fdeab7');
		$('.five').css('background-color','#fdeab7');
		$('.six').css('background-color','#fdeab7');
		$('.sidebar').hide();
		$('.sidebar2').fadeIn(1000);
		$('.sidebar3').hide();
		$('.sidebar4').hide();
		$('.sidebar5').hide();
		$('.sidebar6').hide();
		$('.group').hide();
		$('.group2').show();
		$('.group3').hide();
		$('.group4').hide();
		$('.group5').hide();
		$('.group6').hide();
	});

	$('.three').click(function(){
		$('.one').css('background-color','#fdeab7');
		$('.two').css('background-color','#fdeab7');
		$('.three').css('background-color','#f2d179');
		$('.four').css('background-color','#fdeab7');
		$('.five').css('background-color','#fdeab7');
		$('.six').css('background-color','#fdeab7');
		$('.sidebar').hide();
		$('.sidebar2').hide();
		$('.sidebar3').fadeIn(1000);
		$('.sidebar4').hide();
		$('.sidebar5').hide();
		$('.sidebar6').hide();
		$('.group').hide();
		$('.group2').hide();
		$('.group3').show();
		$('.group4').hide();
		$('.group5').hide();
		$('.group6').hide();
	});

	$('.four').click(function(){
		$('.one').css('background-color','#fdeab7');
		$('.two').css('background-color','#fdeab7');
		$('.three').css('background-color','#fdeab7');
		$('.four').css('background-color','#f2d179');
		$('.five').css('background-color','#fdeab7');
		$('.six').css('background-color','#fdeab7');
		$('.sidebar').hide();
		$('.sidebar2').hide();
		$('.sidebar3').hide();
		$('.sidebar4').fadeIn(1000);
		$('.sidebar5').hide();
		$('.sidebar6').hide();
		$('.group').hide();
		$('.group2').hide();
		$('.group3').hide();
		$('.group4').show();
		$('.group5').hide();
		$('.group6').hide();
	});

	$('.five').click(function(){
		$('.one').css('background-color','#fdeab7');
		$('.two').css('background-color','#fdeab7');
		$('.three').css('background-color','#fdeab7');
		$('.four').css('background-color','#fdeab7');
		$('.five').css('background-color','#f2d179');
		$('.six').css('background-color','#fdeab7');
		$('.sidebar').hide();
		$('.sidebar2').hide();
		$('.sidebar3').hide();
		$('.sidebar4').hide();
		$('.sidebar5').fadeIn(1000);
		$('.sidebar6').hide();
		$('.group').hide();
		$('.group2').hide();
		$('.group3').hide();
		$('.group4').hide();
		$('.group5').hide();
		$('.group6').show();
	});

	$('.six').click(function(){
		$('.one').css('background-color','#fdeab7');
		$('.two').css('background-color','#fdeab7');
		$('.three').css('background-color','#fdeab7');
		$('.four').css('background-color','#fdeab7');
		$('.five').css('background-color','#fdeab7');
		$('.six').css('background-color','#f2d179');
		$('.sidebar').hide();
		$('.sidebar2').hide();
		$('.sidebar3').hide();
		$('.sidebar4').hide();
		$('.sidebar5').hide();
		$('.sidebar6').fadeIn(1000);
		$('.group').hide();
		$('.group2').hide();
		$('.group3').hide();
		$('.group4').hide();
		$('.group5').show();
		$('.group6').hide();
	});
});
